version: "2"

run:
  timeout: 5m

linters-settings:
  govet:
    check-printf: true
    enable-all: true
  errcheck:
    check-blank: true

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - goconst
    - gocritic
    - revive
    - whitespace
    - bodyclose
    - dogsled
    - durationcheck
    - copyloopvar
    - misspell
    - nolintlint
    - unconvert
    - wastedassign


formatters:
  disable-all: true
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

